version: '3.7'

services:
  mysql:
    container_name: ari_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_lampp
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_lampp_network

networks:
  adm_lampp_network:
